name: Node CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12, 14, 16, 17]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node_version }}

    - name: npm install
      run: npm install
    - name: build
      run: npm run build --if-present
    - name: test
      run: npm test
